### PR TITLE
Fix HTTPS mixed content issue

### PR DESCRIPTION
**Pull request by HLFH**
Hi,

@hikalkan 

As you can see, it fixes HTTPS mixed content issue.

Thanks to merge.

Sincerely,
HLFH

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you very much. Does that cause a problem for HTTP?

**Comment by HLFH** [comment]
@hikalkan No, **it does not cause any problem with HTTP**. It's better to enforce HTTPS for the fonts, even if you still use HTTP. Soon, HTTP [will be marked as non-secure](https://www.chromium.org/Home/chromium-security/marking-http-as-non-secure). It's better to begin the switch. IMHO https://github.com/hikalkan/jtable/pull/1888 is a better fix than  #1765.

**Comment by HLFH** [comment]
@hikalkan Hi. Any news?

**Comment by hikalkan** [comment]
Thank you very much.

**Pull request merged**
